### ISSUE TITLE
I can't static link this repository

### ISSUE THREAD

**Issue by git123hub** [temp-TPT-mod-1/The-Powder-Toy-mod-fork#1]
@jacob1 and @HydroH, can you help this issue?

**Comment by jacob1** [comment]
Are you using Visual Studio, or MinGW?

If you are using MinGW, you need to upload some files. What is the exact compiler output that gets printed? Also, upload config.log somewhere.

If you are using Visual Studio, just post the compiler output somewhere.

**Comment by git123hub** [comment]
@jacob1 I using MinGW, not VS.
config.log: https://github.com/temp-TPT-mod-1/TPT-outputs/blob/master/config.log
compile output: https://github.com/temp-TPT-mod-1/TPT-outputs/blob/master/compiler%20output.txt

**Comment by jacob1** [comment]
Have you tried scons --clean yet? That will delete old files and caches that might break it.

The error seems to be that it can't find SDL, but according to config.log it was able to find SDL before. Did you change anything?

I also see you are passing in -static-libgcc. While that's fine and should work, perhaps you could try it once without that. If --clean doesn't work,

**Comment by git123hub** [comment]
@jacob1 How to compile to "libsdl.a"?

**Comment by jacob1** [comment]
I'm not really sure what you did, but it should be part of the guide:
http://powdertoy.co.uk/Wiki/W/Compiling_for_Windows_with_scons.html

Quote:
"Now we need to get a few libraries to compile TPT successfully. The others you need are SDL, Lua, and fftw. They can't be downloaded so easily, so you have to download them manually here:
[MingwLibraries.zip](https://drive.google.com/uc?id=0B1XWtCTn2YPAZ3dqSU5CbjE4OXM&export=download)
Copy both of the folders into your C:\MinGW "

**Comment by git123hub** [comment]
> [MingwLibraries.zip](https://drive.google.com/uc?id=0B1XWtCTn2YPAZ3dqSU5CbjE4OXM&export=download)
I unable to access google.

**Comment by jacob1** [comment]
https://starcatcher.us/TPT/MingwLibraries.zip
